<?php

namespace Modules\TollGate\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Modules\Location\Models\Location;
use Modules\TollGate\Models\TollGate;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\Modules\TollGate\Models\TollGate>
 */
class TollGateFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {
        return [
            'name' => fake()->word(),
            'location_id' => Location::factory()->create()->id,
        ];
    }
    public function newModel(array $attributes = [])
    {
        $model = new TollGate();
        return new $model($attributes); // TODO: Change the autogenerated stub
    }

}
