<?php

namespace Modules\Location\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Modules\Location\Models\Location;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\Modules\Location\Models\Location>
 */
class LocationFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {
        return [
            'name' => fake()->word(),
            'entrance_limit' => fake()->numberBetween(1, 10),
            'price' => fake()->numberBetween(1000, 10000),
            'user_entrance_limit' => fake()->numberBetween(1, 10),
        ];
    }

    public function newModel(array $attributes = [])
    {
        $model = new Location();
        return new $model($attributes); // TODO: Change the autogenerated stub
    }

}
